### ISSUE TITLE
structurethreader not multithreading

### ISSUE THREAD

**Issue by jkreinz** [StuntsPT/Structure_threader#81]
Hi there,

I'm trying to run structure_threader for faststructure enabling multithreading. However when I execute the following command, the commands that are written to screen shows no parallelization as does my job monitor. Any advice for getting multithreading working would be appreciated.

`structure_threader run -i filtered_dustmasked2_pruned.bed -fs ~/software/fastStructure/structure.py -K 5 -t 40 --ind indfile.txt -o threadedrun_logistic --extra_opts prior=logistic --extra_opts seed=123
`

written to screen:

INFO: Running: python2 /ohta/julia.kreiner/software/fastStructure/structure.py -K 5 --input /fast_disk/julia/filtered_dustmasked2_pruned --output /fast_disk/julia/threadedrun_logistic/fS_run_K --format bed --seed 1235813 --seed=123
INFO: Running: python2 /ohta/julia.kreiner/software/fastStructure/structure.py -K 4 --input /fast_disk/julia/filtered_dustmasked2_pruned --output /fast_disk/julia/threadedrun_logistic/fS_run_K --format bed --seed 1235813 --seed=123
INFO: Running: python2 /ohta/julia.kreiner/software/fastStructure/structure.py -K 1 --input /fast_disk/julia/filtered_dustmasked2_pruned --output /fast_disk/julia/threadedrun_logistic/fS_run_K --format bed --seed 1235813 --seed=123
INFO: Running: python2 /ohta/julia.kreiner/software/fastStructure/structure.py -K 3 --input /fast_disk/julia/filtered_dustmasked2_pruned --output /fast_disk/julia/threadedrun_logistic/fS_run_K --format bed --seed 1235813 --seed=123
INFO: Running: python2 /ohta/julia.kreiner/software/fastStructure/structure.py -K 2 --input /fast_disk/julia/filtered_dustmasked2_pruned --output /fast_disk/julia/threadedrun_logistic/fS_run_K --format bed --seed 1235813 --seed=123

**Comment by StuntsPT** [comment]
Hi @jkreinz . Thank you for reporting this.
The issue seems to be that you are trying to run 5 jobs (K=5) on 40 threads (-t=40), and *Structure_threader* cannot do that.
What *Structure_threader* does is split any jobs (or value of K) that would normally be run sequentially, into parallel threads. That means that for `K=5` *Structure_threader* will at most be able to use 5 threads (which, according to the output you post, seems to be the case).
Sorry, but it really is a limitation of the wrapper. In order to use more threads than values of K, we'd have to rewrite `fastStructure`. 
(Note that on `STRUCTURE`, this limitation is mitigated, since each run needs replicates which can be further threaded. eg. K=5 with 10 replicates can be run on up to 50 threads).

On a related note, I have noticed you are using multiple `--extra_opts` parameters. If you do this, only the last one is used, and any others are lost.  In order to pass multiple "extra options", it should be done like this: `--extra_opts "prior=logistic seed=123"`.

However, in the latest version of *Structure_threader*, the `seed` option can (and should) be passed directly, like this: `--seed 123`, without need to use the `--extra_opts` parameter.

I'm sorry to disappoint you regarding the number of threads, but there is really not much we can do regarding that. At least I hope the command line "tips" are helpful.
