### ISSUE TITLE
structure_threader not using all available cores

### ISSUE THREAD

**Issue by oospina** [StuntsPT/Structure_threader#85]
Hi all!
I'm running structure_threader on a cluster using the Slurm scheduler. I ask Slurm for 77 cores, in order to run K=2 to K=8, 10 reps/K. The run proceeds and after a couple of days produces output. Nevertheless, I note that I get this warning:

`WARNING: Number of specified threads is higher than the available ones. Adjusting number of threads to 8, which is the total number of CPUs (physical and logical) on this machine.`

And, I was wondering if perhaps I am wasting resources and the run could go actually faster.

I use the following Slurm script:

```
#!/bin/bash

#SBATCH --job-name="FL1SNP_struct_prelim"
#SBATCH -n 77
#SBATCH -p genacc_q
#SBATCH -t 14-00:00:00

module load python3

structure_threader run -Klist {2..8} -R 10 -i ~/reinf_struct_K2-8_FL_ONESNPs_MOREREPS/input/T548_ONESNPs_FL.stru -o ~/reinf_struct_K2-8_FL_ONESNPs_MOREREPS/results/ -t 70 -st ~/structure_console/structure --params ~/reinf_struct_K2-8_FL_ONESNPs_MOREREPS/input/mainparams
```

Thanks in advance for the help!

Oscar.

**Comment by StuntsPT** [comment]
Hi @oscaredd .
I've looked into your issue and I'm afraid I don't have a full solution for you (but read on fora possible workaround).
*Structure_threader* uses the `multiprocessing` module internally to spread jobs across multiple threads. This is somewhat similar to what Slurm does, but on a different level. In short, slurm will not provide you with a single system node with 77 cores, but rather several nodes with `n` cores each (in this case, 8 cores per node apparently) [here](https://stackoverflow.com/questions/39974874/using-pythons-multiprocessing-on-slurm) and [here](https://stackoverflow.com/questions/32594734/slurm-multiprocessing-python-job) are some references.
*Structure_threader* will only see each node, and therefore, is limited to the 8 cores of each of these nodes. There is really not much that can be done about that AFAIK.
What you *might* try, however is to request a single task from slurm with as many cores as you can. Something like this:
```
#SBATCH -N 1      # nodes requested
#SBATCH -n 1      # tasks requested
#SBATCH -c 40    # cores requested
```
See how close you can get to 80 (you probably want K=1 too for evanno's test) to effectively "paralellize" all your runs. If this works, your issue is solved.
If your cluster does not have a 80 core node available, try to break it in smaller parts - Say you get 40 cores, ask 2 jobs, one for K 1-4 and another one for K 5-8. Use the `--no-tests 1` flag to avoid running Evanno's test on incomplete data.
Then merge the data on your `results` directories, so that you get one directory that contains all the results. This should be done outside the Slurm cluster.
After this edit the file `~/.local/lib/python3.7/site-packages/structure_threader/structure_threader.py` (or similar, you have to find where *Structure_threader* is installed) and comment line `298`, to make it look like this:

```python
#    structure_threader(wrapped_prog, arg)
```

This will disable *Structure_threader* from running STRUCTURE.
Finally, run *Structure_threader* again, with the full command - similar to this (adjust to your case):

```bash
structure_threader run -K 8 -R 10 -i ~/reinf_struct_K2-8_FL_ONESNPs_MOREREPS/input/T548_ONESNPs_FL.stru -o ~/reinf_struct_K2-8_FL_ONESNPs_MOREREPS/results/ -t 1 -st ~/structure_console/structure --params ~/reinf_struct_K2-8_FL_ONESNPs_MOREREPS/input/mainparams
```

If all goes well, after this command, *Structure_threader* will pick up where Slurm left off. It will run Evanno's test, and draw your plots.

Best of luck!

Francisco

**Comment by oospina** [comment]
Thanks for the reply Francisco.
The folks that provide support for our cluster just confirmed what you say. They also suggested to partition my job (which you are explaining now how to do it).
Thanks!

Oscar.

**Comment by StuntsPT** [comment]
No problem.
I'll close the issue for now, but feel free to ask any further related questions. I'll help if I can.
