### ISSUE TITLE
ERROR: moving to final location failed

### ISSUE THREAD

**Issue by thesnakeguy** [StuntsPT/Structure_threader#89]
Hi,

I encountered a problem while running structure_threader that is likely related to the following message in the log:

error in the terminal:
`CRITICAL: 11 alstructure runs exited with errors. Check the log files of the following output files:
`

log info regarding the issue:

mv: cannot move '/home/pablo/R/x86_64-conda_cos6-linux-gnu-library/3.6/00LOCK-xml2/00new/xml2' to '/home/pablo/R/x86_64-conda_cos6-linux-gnu-library/3.6/xml2': Permission denied
ERROR:   moving to final location failed
ERROR: dependency ‘xml2’ is not available for package ‘roxygen2’
* removing ‘/home/pablo/R/x86_64-conda_cos6-linux-gnu-library/3.6/roxygen2’
ERROR: dependency ‘xml2’ is not available for package ‘rversions’
* removing ‘/home/pablo/R/x86_64-conda_cos6-linux-gnu-library/3.6/rversions’
ERROR: dependencies ‘roxygen2’, ‘rversions’ are not available for package ‘devtools’
* removing ‘/home/pablo/R/x86_64-conda_cos6-linux-gnu-library/3.6/devtools’

The downloaded source packages are in
	‘/tmp/RtmpXmy99H/downloaded_packages’
Error in library("devtools") : there is no package called ‘devtools’
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘alstructure’
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
3: In install.packages("devtools") :
  installation of package ‘xml2’ had non-zero exit status
4: In install.packages("devtools") :
  installation of package ‘roxygen2’ had non-zero exit status
5: In install.packages("devtools") :
  installation of package ‘rversions’ had non-zero exit status
6: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status
Execution halted

I have set the permissions to the /home/pablo/R/ directory and subdirectories to 777 (sudo chmod -R 777 /home/pablo/R), but I get the same log messages. 
Any recommandations?

Kind regards,
Pablo

**Comment by StuntsPT** [comment]
Dear Pablo,

Thank you for reporting the issue. I **suspect** it might be related to the version of R you are using.
Although in the past I had `ALStructure` working with R 3.6, this package requires the use of devtools, which makes it a tad more unstable than what I would like.
It seems to me that one of the dependencies in the dependency tree (which is huge, by the way) must have been updated to require at least R 4.X, which is consistent with the error you are reporting.
Now that you mention it, I had some tests in the suite fail for *ALStructure* yesterday, and I wasn't sure why. But it was automatically solved when I updated R to version 4 (since I couldn't find a small docker image with both python 3.7 and R 3.6, but I digress).

I'd recommend trying to install a new version of R using conda (as you already seem to be doing), probably using a new environment, just to make sure you don't break any other packages you already have running, and trying *Structure_threader* again.

Please let me know if that worked out for you.

**Comment by thesnakeguy** [comment]
Hi StuntsPT,

Many thanks for the quick reply! I created a new environment and installed R 4.0 from the conda-forge channel. Unfortunately I get the same error again. 

**This might be what is causing the issue?:**
mv: cannot move '/home/pablo/R/x86_64-conda-linux-gnu-library/4.0/00LOCK-xml2/00new/xml2' to '/home/pablo/R/x86_64-conda-linux-gnu-library/4.0/xml2': Permission denied
ERROR:   moving to final location failed

**This is the traceback in the prompt:**
Traceback (most recent call last):
  File "/home/pablo/miniconda3/envs/structure/bin/structure_threader", line 8, in <module>
    sys.exit(main())
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/structure_threader.py", line 349, in main
    full_run(arg)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/structure_threader.py", line 312, in full_run
    create_plts(wrapped_prog, bestk, arg)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/structure_threader.py", line 230, in create_plts
    indfile=arg.indfile, bw=arg.blacknwhite, use_ind=arg.use_ind)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 1004, in main
    klist = PlotList(result_files, fmt, popfile=popfile, indfile=indfile)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 406, in __init__
    kobj = PlotK(fpath, self.fmt)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 107, in __init__
    parse_methods[self.fmt]()
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 314, in _parse_alstructure
    self.qvals = np.genfromtxt(self.file_path, skip_header=1, delimiter=",")
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/pablo/miniconda3/envs/structure/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: /mnt/e/Processed_data_FFIPM/Italy/structurethreader/alstr_K2 not found.

What do you think? 
Again, thanks for helping me out!

Cheers,
Pablo

**Comment by StuntsPT** [comment]
Hello again Pablo,
The simple solution was worth a shot, but I guess it just wasn't enough.
Lets try to dig deeper.
First of all, are you using WSL (Windows Subsystem for Linux)? This error seems to crop up when using this emulation layer.
This could also be related to a lock condition. Let's try to work around that.
First, activate your new conda environment;
Then start a new `R` console and type the following:

```R
Sys.setenv(R_INSTALL_STAGED = FALSE)  # Disable the lock
install.packages("devtools")  # Manually install devtools
```

Then exit the console, and try running *Structure_threader* again, to see if it gets past the install stage of *ALStructure*.
If this fails to solve your problem, I'm going to need a small example on how to reproduce the issue.
For that I will need 2 things:
1. The commands you used to create and activate your conda environment;
2. The exact command you used to trigger the issue

Reproducing the issue locally should enable me to identify what is causing the issue and understand how to work around it.

**Comment by thesnakeguy** [comment]
Hi Francisco,

Yup, I am using WSL.  I tried the method above but to no avail. Here is the info requested:

1. Create and activate the environment:
   conda create -n structure python=3.6
   conda activate structure
   conda config --add channels conda-forge
   conda install -c conda-forge r-base
   pip install structure_threader

2. The command that triggers the issue:
 structure_threader run -i ./italy2020_rem10_miss070.vcf -o ./structurethreader -K 12 -t 12 --ind ./regpopcodes.txt -als ~/miniconda3/envs/structure/bin/alstructure_wrapper.R

If you need anything more, please let me know. Many thanks!

Cheers,
Pablo

**Comment by StuntsPT** [comment]
Ok, I definitely can't reproduce the issue on any of my machines using your steps. This seems to be indeed a WSL issue.
(I don't have access to any windows machines to test myself).
Some web searching, seems to indicate `xml2` as the issue, so maybe try to install it manually:

```R
Sys.setenv(R_INSTALL_STAGED = FALSE)  # Disable the lock
install.packages("xml2")  # Manually install xml2
```

If this command throws an error, maybe try this alternative:

```R
install.packages("xml2", dependencies=TRUE, INSTALL_opts = c('--no-lock'))
```

If these commands do not error out, than try running *Structure_threader* again. It is possible that other similar errors crop up during dependency installation due to WSL issues. If this is the case, every time you get an error, check the logs for the problematic package names, and try to install them manually.
Other than this, I can only recommend performing the analyses on a GNU/Linux system, or maybe even on windows itself without the WSL compatibility layer (I have not tested ALStructure in windows though, but *Structure_threader* should work fine).

I'm sorry I don't really have a better solution for you. WSL is a strange beast indeed (and definitely not 100% bug-free).

**Comment by StuntsPT** [comment]
Oh, and I almost forgot. You may need to install `libgit2` using conda too!

```bash
conda install -c conda-forge libgit2
```

**Comment by thesnakeguy** [comment]
Hi Francisco, 

Thanks for the quick reply and the suggestions! I installed all of the packages that had non-zero exit status in the log (see first post) manually, installed libgit2 like you mentioned and now I seem to get another error. To me it looks like it might have something to do with the "NA"s in my .tsv file.

  [1] "/mnt/e/Processed_data_FFIPM/Italy/italy2020_rem10_miss070.tsv"
  Loading required package: alstructure
  Loading required package: lfa
  Error in eigen(1/m * t(X) %*% X - D) : infinite or missing values in 'x'
  Calls: alstructure_wrapper -> alstructure -> estimate_F -> lse -> eigen
  Execution halted

Sorry for annoying you with this issue! But still hoping for a fix using my WSL.

Cheers,
Pablo

**Comment by StuntsPT** [comment]
Ok, we are indeed getting somewhere!
I remember having *ALStructure* erroring out on me with that same message when trying to estimate the best value of K (which requires the input data to have no missing data). In fact I [opened a bug report for it](https://github.com/StoreyLab/alstructure/issues/2) in the *ALStructure* repository, but never got a reply.
I suppose a few other things could explain this when analysing data for a pre-set K.

1. Your matrix has a SNP which is 100% missing data;
2. My conversion script from VCF to TSV is not working as intended on your VCF file;

If it is the 1st option, you can check it yourself. =-) But by the looks of your filename, it has already undergone some filtering, and therefore seems highly unlikely.
To check the second option, I will require that you post the first 10 lines of the TSV file, along with the last line of the VCF header (the one that starts with `#CHROM`) plus the first 10 lines with SNPs (the first lines that don't start with a `#`). Don't forget to anonymize your individual names if the data fragment is sensitive!
This information should suffice to see if my script is missing some corner case.
Oh, and since you are at it, please also scan your TSV file for lines that contain only "NA". If one such line exists, please try to match it to the VCF line, and post them both.  =-)

**Comment by thesnakeguy** [comment]
Hi,

1. Good suggestion!
   t <- read.csv("italy2020_rem10_miss070.tsv", header = FALSE, sep = "\t")
   t$ID <- c(1:dim(t)[1])
   t$All_NA <- apply(t, 1, function(x) all(is.na(x)))
   table(t$All_NA)
            -> 24 lines were TRUE, while no multiallelic markers should be present in my vcf after filtering...
            -> I checked these positions in the VCF:
                     grep -o '^[^#]*' italy2020_rem10_miss070.vcf | awk 'NR==pos'
                     -->  Turns out that these 24 positions had more than 2 alleles. After removing them structure_threader worked just 
                             fine!

Many thanks for your help! Case closed :)

Cheers,
Pablo

**Comment by StuntsPT** [comment]
Awesome!
Enjoy the interpretation step! =-)
